#pragma once
#undef  PRODUCT_ID
#define PRODUCT_ID    0x24C0

#undef  PRODUCT
#define PRODUCT    EEPad 23U (FW_VER)

#undef  MATRIX_ROWS
#define MATRIX_ROWS 6
#undef  MATRIX_COLS
#define MATRIX_COLS 4
#define MATRIX_KEYS 24

#define APC_ENABLE

#undef  BLE_NAME
#define BLE_NAME "EEPad_23U BLE"

#define EEVEE_INDICATOR_FUCTION USB_LED_NUM_LOCK
#define UNLOCK_KEY1 KC_P4
#define UNLOCK_KEY2 KC_P6
#define PAD00_ENABLE

#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define FLASH_KEYMAP_COUNT 2
//#define FLASH_KEYMAP8_COUNT 1
#define VIAL_KEYBOARD_UID {0x2E, 0xE6, 0x0E, 0x23, 0x34, 0xEF, 0x99, 0x3F}
